### ISSUE TITLE
Snapin is PoSh20

### ISSUE THREAD

**Issue by Plork** [f5devcentral/f5-icontrol-powershell-snapin#1]
any plans to update the snapin to a module? Since snapin is a technique even Microsoft regrets ;)

**Comment by spuder** [comment]
+1 
Additional information on why snapins have gone the way of the dodo, and modules are the future

http://blog.codeinside.eu/2013/03/08/powershell-snapins-vs-modules/

**Comment by adam-f5** [comment]
Repository Archived
