### ISSUE TITLE
Not Register DLL iControlSnapin

### ISSUE THREAD

**Issue by amroth3003** [f5devcentral/f5-icontrol-powershell-snapin#11]
Running a transacted installation.

Beginning the Install phase of the installation.
See the contents of the log file for the C:\Program Files\f5 networks\iControlSnapIn.dll assembly's progress.
The file is located at C:\Program Files\f5 networks\iControlSnapIn.InstallLog.
Installing assembly 'C:\Program Files\f5 networks\iControlSnapIn.dll'.
Affected parameters are:
   logtoconsole = true
   assemblypath = C:\Program Files\f5 networks\iControlSnapIn.dll
   logfile = C:\Program Files\f5 networks\iControlSnapIn.InstallLog
An exception occurred while trying to find the installers in the C:\Program Files\f5 networks\iControlSnapIn.dll assembly.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Aborting installation for C:\Program Files\f5 networks\iControlSnapIn.dll.

An exception occurred during the Install phase.
System.InvalidOperationException: Unable to get installer types in the C:\Program Files\f5 networks\iControlSnapIn.dll assembly.
The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..

The Rollback phase of the installation is beginning.
See the contents of the log file for the C:\Program Files\f5 networks\iControlSnapIn.dll assembly's progress.
The file is located at C:\Program Files\f5 networks\iControlSnapIn.InstallLog.
Rolling back assembly 'C:\Program Files\f5 networks\iControlSnapIn.dll'.
Affected parameters are:
   logtoconsole = true
   assemblypath = C:\Program Files\f5 networks\iControlSnapIn.dll
   logfile = C:\Program Files\f5 networks\iControlSnapIn.InstallLog
An exception occurred while trying to find the installers in the C:\Program Files\f5 networks\iControlSnapIn.dll assembly.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Aborting installation for C:\Program Files\f5 networks\iControlSnapIn.dll.
An exception occurred during the Rollback phase of the System.Configuration.Install.AssemblyInstaller installer.
System.InvalidOperationException: Unable to get installer types in the C:\Program Files\f5 networks\iControlSnapIn.dll assembly.
The inner exception System.Reflection.ReflectionTypeLoadException was thrown with the following error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information..
An exception occurred during the Rollback phase of the installation. This exception will be ignored and the rollback will continue. However, the machine might not fully revert to its initial state after the rollback is complete.

The Rollback phase completed successfully.

The transacted install has completed.
The installation failed, and the rollback has been performed.

C:\Windows\Microsoft.NET\Framework64\v4.0.30319>

**Comment by adam-f5** [comment]
Repository Archived
