### ISSUE TITLE
Update classes to be compatible with the LocalLBPool interface

### ISSUE THREAD

**Issue by csharris** [f5devcentral/f5-icontrol-powershell-snapin#2]
Since version 11.0.0, the interface `LocalLBPoolMember` has been deprecated and the functionality has moved into the `LocalLBPool` interface. I noticed this change while looking at the WSDL at this partial link: [/iControl/iControlPortal.cgi?WSDL=LocalLB.PoolMember](/iControl/iControlPortal.cgi?WSDL=LocalLB.PoolMember). 

Are there any plans to add classes similar to those in `iControlSnapIn.CmdLet.LTM.PoolMember` to use the types declared in the `LocalLBPool` interface? 

At this point, if I wanted to use the command `Set-F5.LTMPoolMemberState`, I'm forced to either supply an object of type `LTMPoolMemberItem` (which is from the old interface), or I need to supply the member which uses the `CommonIPPortDefinition` type. It would be fantastic if these commands supported types from the `LocalLBPool` interface and the `CommonAddressPort` type.

**Comment by joepruitt** [comment]
Honestly, the cmdlets were originally written as some simple use cases and I quickly found out that they didn't completely satisfy ~75% of the users full needs.  So, I've suggested migrating to using Get-F5.iControl and internal interfaces directly.  It's doesn't give you all that native cmdlets do, but you do have access to all of the types in the native library.  So, for pool you can use (Get-F5.iControl).LocalLBPool.get_member();   If you have additional cmdlets you would like seen added, feel free to submit a set of changes and I'll get them merged in.

**Comment by csharris** [comment]
Thanks for responding Joe. I'll go ahead and use the library directly for what I'm trying to accomplish :)

**Comment by adam-f5** [comment]
Repository Archived
