### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by spuder** [f5devcentral/f5-icontrol-powershell-snapin#4]
Whenever I run the `setupSnapIn.ps1` script it fails to install

```
PS C:\Users\sowen\Documents\f5-icontrol-powershell-snapin> .\setupSnapIn.ps1
Registering iControlSnapin.dll on platform ''
Microsoft (R) .NET Framework Installation utility Version 2.0.50727.8007
Copyright (c) Microsoft Corporation.  All rights reserved.

Exception occurred while initializing the installation:
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\sowen\Documents\f5-icontrol-powershell-snapin\iControlSnapin.dll' or one of its dependencies. The system cannot find the file specified..
Registering iControlSnapin.dll on platform '64'
Microsoft (R) .NET Framework Installation utility Version 2.0.50727.8007
Copyright (c) Microsoft Corporation.  All rights reserved.

Exception occurred while initializing the installation:
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\sowen\Documents\f5-icontrol-powershell-snapin\iControlSnapin.dll' or one of its dependencies. The system cannot find the file specified..
```

It is complaining that iControlSnapin.dll is missing. Where do I get that dll?

**Comment by spuder** [comment]
I've followed the instructions here and unziped the file to c:\Program Files\F5 Networks\iControlSnapIn

The iControlSnapIn.dll is now present, however even after running ./setupSnapin.ps1, I still get this error: 

```
PS C:\Program Files\F5 Networks\iControlSnapIn> Add-PSSnapin iControlSnapIn
Add-PSSnapin : Cannot load Windows PowerShell snap-in iControlSnapIn because of the following error: Could
not load file or assembly 'file:///C:\Program Files\F5 Networks\iControlSnapIn\iControlSnapIn.dll' or one of
its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Add-PSSnapin iControlSnapIn
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (iControlSnapIn:String) [Add-PSSnapin], PSSnapInException
    + FullyQualifiedErrorId : AddPSSnapInRead,Microsoft.PowerShell.Commands.AddPSSnapinCommand
```

Following[ these instructions](http://stackoverflow.com/a/21770848/1626687) does not work. Still can't get the snap in working

**Comment by spuder** [comment]
Looks like I had to unblock the zip file _before_ extracting

![screenshot 2016-08-22 16 38 00](https://cloud.githubusercontent.com/assets/242382/17874126/de2b11e0-6886-11e6-93a9-4c5954501aa7.png)

**Comment by ghost** [comment]
If you have performed the instructions as suggested above

and if you still get the error.

The most likely cause would be the permission to the below registry path to your current account. You will need to provide full control to the registry HKEY_LOCAL_MACHINE\Software\Microsoft\PowerShell\1\PowerShellSnapIns .

Upon having full control, then re run the setupSnapIn.ps1 and you should be all set to proceed further.
