### ISSUE TITLE
Convert to powershell module

### ISSUE THREAD

**Issue by timriker** [f5devcentral/f5-icontrol-powershell-snapin#9]
PSSnapin is not supported in Powershell 6 and newer including platform portable versions. Can this get converted to a Powershell Module using .NET Core for use on other platforms?

Reference info:
- https://www.darkoperator.com/blog/2013/2/19/powershell-basics-extending-the-shell-with-modules-and-snapi.html
- https://github.com/PowerShell/PowerShell/blob/master/docs/BREAKINGCHANGES.md#custom-snap-ins
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pssnapins?view=powershell-5.1
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-6

**Comment by auctivagit** [comment]
I'm also interested in this... we faced the same issue some time ago. I'd like to see this officially supported, but I dont expect it. It seems the newer approach is to use the REST api. Here's a recently featured article wrapping this API in a powershell module. https://devcentral.f5.com/codeshare/powershell-module-for-the-f5-ltm-rest-api We'd looked into swapping previously, but we had issues with the REST api, IIRC 1) REST access was only accessible to admin users for some reason 2) we were getting lockups when making too many REST api calls.. But its been at least a year, and might be worth looking into again for us. We solved the issue by writing our own powershell module that wrapped the iControl.dll assembly and invoked the methods directly.

**Comment by nheath** [comment]
I'm also interested in this... we faced the same issue some time ago. I'd like to see this officially supported, but I dont expect it. It seems the newer approach is to use the REST api. Here's a recently featured article wrapping this API in a powershell module. https://devcentral.f5.com/codeshare/powershell-module-for-the-f5-ltm-rest-api We'd looked into swapping previously, but we had issues with the REST api, IIRC 1) REST access was only accessible to admin users for some reason 2) we were getting lockups when making too many REST api calls.. But its been at least a year, and might be worth looking into again for us. We solved the issue by writing our own powershell module that wrapped the iControl.dll assembly and invoked the methods directly.

**Comment by timriker** [comment]
Our issue is the same. It seems a guest user can use the old SOAP interface, but I've not been successful in having a guest user use much on the REST interface. I would be interested in your iControll.dll module wrapper.

**Comment by timriker** [comment]
It looks like this snapin and the iControl.dll module use Windows Forms which is NOT supported under .NET core, which means the entire implementation is not portable.

It is possible to use the powershell Invoke-RestMethod to directly call iControl SOAP interfaces. I may convert to native SOAP calls and skip the iControl Snapin in order to gain portability.

**Comment by adam-f5** [comment]
Repository Archived
